# Generated by Django 3.1.3 on 2020-12-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrApp', '0003_auto_20201224_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bjpdata',
            old_name='Session',
            new_name='Sess',
        ),
    ]
