# Generated by Django 3.1.3 on 2020-12-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
