# Generated by Django 3.1.3 on 2020-12-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthApp', '0007_auto_20201207_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reports',
        ),
        migrations.AddField(
            model_name='user',
            name='reports',
            field=models.ManyToManyField(blank=True, to='userAuthApp.report'),
        ),
    ]
