# Generated by Django 3.1.3 on 2020-12-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthApp', '0009_reportdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reportData',
        ),
    ]
