# Generated by Django 3.0.3 on 2020-05-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('Class', models.IntegerField()),
                ('subject', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='student_homework')),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('Class', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='info')),
            ],
        ),
        migrations.CreateModel(
            name='lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('Class', models.IntegerField()),
                ('subject', models.CharField(max_length=15)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('Class', models.IntegerField()),
                ('subject', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='notes')),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('date', models.DateField()),
                ('notice_msg', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='school_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('roll_no', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=25)),
                ('Class', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_hw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('Class', models.IntegerField()),
                ('subject', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='teacher_hw')),
            ],
        ),
        migrations.CreateModel(
            name='teacher_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
