# Generated by Django 3.0.3 on 2020-11-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.FileField(upload_to='uploads')),
            ],
        ),
    ]
