# Generated by Django 3.0.3 on 2020-11-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_auto_20201104_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycontent',
            name='img',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
