# Generated by Django 3.0.3 on 2020-11-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_auto_20201104_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycontent',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
