# Generated by Django 3.0.3 on 2020-03-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Gender', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Password', models.CharField(max_length=20)),
                ('Locality', models.CharField(max_length=20)),
            ],
        ),
    ]
