# Generated by Django 3.0.3 on 2020-03-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shops_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Gender', models.CharField(max_length=10)),
                ('Shopname', models.CharField(max_length=50)),
                ('Service', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Password', models.CharField(max_length=20)),
                ('Locality', models.CharField(max_length=20)),
            ],
        ),
    ]
