# Generated by Django 3.0.3 on 2020-05-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0002_raise_issue_trade_feed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='raise_issue',
        ),
    ]
